### PR TITLE
WIP deflare: only load ChIPS when needed

### PR DESCRIPTION
**Pull request by DougBurke**
This is a simple, but ugly, hack. See #113 for motivation.

**EDITED TO ADD** we are planning to move to Matplotlib for deflare, so this isn't needed, but I'm leaving it up for the moment so we don't forget about it.

### CODE REVIEW

**Comment by DougBurke** [comment]
I *think* that the wrap up function only uses chips if plot is set. Or did
I mis-read the code / not test this properly (entirely possible)?

**Comment by kglotfelty** [comment]
I think the `import pychips` w/in the method restricts the scope (so it's only available within that method).

I did a quick merge of this PR in `/pool7/kjg/` using the (random) lightcurve file in that dir and I get:

```bash
% deflare in=lc.fits out=out.gti  plot=no save=goo.ps mode=h  |& tee run.log
...
  ((time >= 259601271.85945001) && (time < 259601273.85945001)) ; 0.00 ksec, bin 1990
  ((time >= 259601278.85945001) && (time < 259601279.85945001)) ; 0.00 ksec, bin 1991

  Exposure time of lightcurve = 9.97 ks
  Filtered exposure time      = 4.08 ks
  DTCOR value                 = 0.98192

Creating GTI file
Created: out.gti
Light curve cleaned using the lc_clean routine.
# deflare (29 March 2018): ERROR name 'pychips' is not defined
```

**Comment by DougBurke** [comment]
Ahh. I hadn't tested plot=no and save=<set>. I think.

**Comment by kglotfelty** [comment]
I also see it with `plot=yes` too .  It looks like it's in the `save` path

```bash
% deflare in=lc.fits"[#row=1100:1200]" out=out.gti plot=yes save=goo.ps mode=h --debug
...
# deflare (29 March 2018): ERROR name 'pychips' is not defined


##### Traceback:

Traceback (most recent call last):
  File "/export/CIAOT/ciaot_install/20180306P3/ciao-4.10/contrib/lib/python3.5/site-packages/ciao_contrib/logger_wrapper.py", line 531, in new_fn
    return fn(*args, **kw)
  File "/export/CIAOT/ciaot_install/20180306P3/ciao-4.10/contrib/bin/deflare", line 239, in deflare
    wrapup(params)
  File "/export/CIAOT/ciaot_install/20180306P3/ciao-4.10/contrib/bin/deflare", line 176, in wrapup
    pychips.print_window(oplot,
NameError: name 'pychips' is not defined
```

**Comment by DougBurke** [comment]
Hmmm. Not sure this is actually addressing the problem I think it should be addressing.

**Comment by DougBurke** [comment]
I'm closing this down since we are removing the use of chips in deflare.

**Pull request closed without merging**
