### PR TITLE
specextract internal changes and bug fix handling blanksky background files

### PR DESCRIPTION
**Pull request by nplee**
addresses suggestions made in #460 for internal updates; updated change log; and fixed a problem with an attempt to generate aspect histograms when a blanksky background is used which should not be done.

### CODE REVIEW

**Comment by DougBurke** [comment]
@nplee - I thought I'd already asked it, but GitHub appears to have eaten it.

There's a conflict with `specextract` here - did you already include some of the changes in #460?

**Comment by nplee** [comment]
yes, this is putting in the suggestions you made on top of what was introduced in #460 plus a bug fix.

**Comment by DougBurke** [comment]
But there's conflicts with `specextract` so I can't merge this.

**Comment by nplee** [comment]
conflicts should be now resolved and mergeable

**Comment by DougBurke** [comment]
@nplee - Github claims it's still in conflict (and there's been no change since your initial commit yesterday):

conflict

**Comment by nplee** [comment]
@DougBurke I've just committed the merge, hopefully it's resolved on your end now

**Pull request merged**
