### PR TITLE
Cleanup chips influences in the lightcurve code

### PR DESCRIPTION
**Pull request by DougBurke**
- remove chips references from the lightcurve code base and documentation
- fix a minor issue whereby underscores in labels would appear as '\_' in the plot (not sure if this is likely to happen, but it's a holdover from the ChIPS support)
- note that the erase argument is no-longer used, but don't remove it in case someone has code that sets it
- similarly the protect argument is no-longer used
- remove use of 'import six'
- minor style changes, as suggested by `pycodestyle`

### CODE REVIEW

**Comment by DougBurke** [comment]
@nplee - can you just look this over to make sure it is okay?

**Comment by DougBurke** [comment]
The PR has been rebased to reflect the latest master branch

**Comment by nplee** [comment]
# @DougBurke changes look good to me (or at least I don't see anything problematic)

**Comment by DougBurke** [comment]
Ta

**Pull request merged**
