### PR TITLE
*search_csc: initial csc2.1 support/branding

### PR DESCRIPTION
**Pull request by kglotfelty**

### CODE REVIEW

**Comment by DougBurke** [comment]
I'm hoping we should get more clarity next week on the new endpoints (but I'm not sure that's relevant here, other than checking the tag name).

**Comment by kglotfelty** [comment]
I also don't know if the list of filetypes is actually correct for 2.1 (for current I just set it to use the 2.0; but didn't check if that was right).  Similarly I don't know if the pre-canned/"default" search results are the same as 2.0 -- will need to see what cscview comes out with when it's actually released.

Probably should have put that in the initial PR comment.

**Comment by DougBurke** [comment]
So, we now have apec results, so there may be a tweak to the spectral data. Other than that I'd expect the queries to be similar (but there's also tweaks to variability, so maybe that will change the variability query). Hmmm.

**Comment by kglotfelty** [comment]
and I'm assuming still no CLI i/f to limsens.

**Comment by DougBurke** [comment]
It looks like we already have CSCCLI access but just **not** advertised ...

```
% wget -O limsens.vot 'http://cda.cfa.harvard.edu/csclimsen/limsen?RA=246.7925&DEC=-24.32027&SR=0.05'
```

where `SR` is in degrees.

**Comment by kglotfelty** [comment]
Last I heard ... that's not supposed to be "public" ... so not something we should be using

See https://icxc.harvard.edu/pipe/catdev/2021/0520.html

**Comment by kglotfelty** [comment]
Humm... and I presume that what's there will need some kind of version/release parameter added?  (Or separate 21 endpoint?)

**Comment by DougBurke** [comment]
That is a question I have yet to had people understand why I ask it...

**Comment by DougBurke** [comment]
I'm going to take this rather than #865 since I think the decision to enable this is likely to have to be done post the release, what with all the other stuff going on.

**Pull request merged**
