### PR TITLE
CIAO 4.14 warm temperature warnings

### PR DESCRIPTION
**Pull request by nplee**
This update is primarily drive by CalDB 4.10.2 and will raise a cautionary note at the end of the run with advice on handling observations >-109 C FP_TEMP after beginning July 2020.

Also internal changes that should eliminate a race condition that would randomly cause response generation to fail while done in parallel.

### CODE REVIEW

**Comment by DougBurke** [comment]
@nplee - do you have a good obsid to test this against?

**Comment by kglotfelty** [comment]
Here's a list of public obsids with FP_TEMP > 164:
```
#fp_temp obs_id 
167.195724490 27292
167.358047490 27293
167.358047490 27294
167.358047490 27295
167.358047490 27305
167.358047490 27306
167.358047490 27307
167.520385740 27281
167.520385740 27282
167.520385740 27283
167.520385740 27284
167.520385740 27285
167.520385740 27286
167.520385740 27290
167.520385740 27291
167.520385740 27296
167.520385740 27297
167.520385740 27298
167.520385740 27299
167.520385740 27308
167.520385740 27309
167.520385740 27310
167.520385740 27311
167.6827240 27287
167.6827240 27288
167.6827240 27289
167.6827240 27300
167.6827240 27301
167.6827240 27302
167.6827240 27303
167.6827240 27304
167.845077510 27274
167.845077510 27275
167.845077510 27276
167.845077510 27277
167.845077510 27278
167.845077510 27279
167.845077510 27280
```

**Comment by nplee** [comment]
@DougBurke using 27306 for the regression test, but Kenny's list helps to expand the set.

**Comment by DougBurke** [comment]
Ta all

**Pull request merged**
