### PR TITLE
specextract enhancements

### PR DESCRIPTION
**Pull request by nplee**
This update includes the use of the most recent HRC RMFs found in the CalDB and the weighted response speed up approach by clipping the sky2tdet WMAP as suggested in #357

### CODE REVIEW

**Comment by DougBurke** [comment]
@nplee - I see this as two featires:

a) HRC RMFs

which are an "obvious" fix (although should we ask the CALDB what the file should be rather than hard-code the value)?

b) the #357 change

which is in the "need to evaluate" category (e.g. what fraction do we suggest to users, what differences does it make in the results, ...).

I haven't looked at the changes yet, but is the WMAP change on or off by default, and can you turn it "off" (ie get the same results as before the change) with a parameter?

**Comment by nplee** [comment]
@DougBurke 

On (a), you're certainly correct that calquiz could be used to query the CALDB instead of the hardcoded RMFs; certainly a better option for future-proofing.

(b) The default behavior is not to apply the clipping, so same results as before. This is controlled by the "wmap_clip" parameter.

**Comment by DougBurke** [comment]
@nplee - I'd like this separated into two: the RMF change and then the WMAP-filtering change. I only want to take the RMF change for this release, and we can have some time to check out the WMAP change. So, priority wise, just focus on a PR with the RMF change for now. Does this sound okay?

**Comment by nplee** [comment]
@DougBurke yes, I'm working out a version with just the RMF changes.

**Comment by nplee** [comment]
@DougBurke the RMF-only update can be found in PR #371

**Pull request closed without merging**
