### PR TITLE
merge_obs: fix sort order when dealing with interleaved mode

### PR DESCRIPTION
**Pull request by kglotfelty**
`merge_obs` (and I guess `reproject_obs`?) sorts the input list of event files based on `TSTART` .

But interleaved mode datasets have the same `TSTART` so the e1 and e2 files can end up in a random order.  This affects things like DTCOR, LIVETIME, etc keywords, and which events show up first in the merged event file.

This change adds appends a sortable token (string) to the end of the TSTART to ensure a deterministic order.

I've chosen to sort so that the e2 file comes first since it is the longer of the two -- that is most events come from the e2 dataset so it's DTCOR/etc are appropriate for more of the events.

## TODO

- Review whether we should actually `dmsort` the event file on `TIME` if it contains both `e1` and `e2`.

### CODE REVIEW

**Comment by kglotfelty** [comment]
This will close #190 if/when completed.

**Comment by DougBurke** [comment]
I haven't looked at the code yet (technically still on "vacation" this morning) but are there any more code changes, or is it WIP for your "do you even dmsort" question?

**Comment by kglotfelty** [comment]
This should be "it" now.  The other sort fileio is the `MJD_|-OBS` thing.

The secondary -- should the file be `dmsort`ed is for another day

**Comment by DougBurke** [comment]
Is it worth adding to the documentation that interleaved mode is now handled correctly?

**Comment by kglotfelty** [comment]
I'm not sure "correctly" is correct.  It's now deterministic ; sometimes e1 would come first some times e2 would be first -- this just ensures e2 is first.

Why e2?  This is the same issue when combining any files where DTCOR is different -- just in the interleaved mode case instead of 0.99 vs. 0.98 kinds of diffs, it's 0.9x vs. 0.09 (ie an order of magnitude) ... what is the correct DTCOR in the merged dataset (and then LIVETIME/EXPOSURE).  e2 is the longer exposure so most events are e2 so the e2 DTCOR is probably "better" ... "correct" is a bit more of a leap.

**Comment by DougBurke** [comment]
"Is it worth adding to the documentation that interleaved mode is now handled consistently?"

**Pull request merged**
